// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0-ULK4XhrQo-HJSuwHLJQwM_I6cOTS8',
    appId: '1:26759593661:web:bcda1eb11cfa44752181d4',
    messagingSenderId: '26759593661',
    projectId: 'mi-vecino-seguro',
    authDomain: 'mi-vecino-seguro.firebaseapp.com',
    storageBucket: 'mi-vecino-seguro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTd-2UY60EUMLPsoTPf0vPS14vrr5u9B8',
    appId: '1:26759593661:android:c77a7ca6806db0252181d4',
    messagingSenderId: '26759593661',
    projectId: 'mi-vecino-seguro',
    storageBucket: 'mi-vecino-seguro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASB2BL-5BSpWCWwyWYSzsVr7P7GbiBOBM',
    appId: '1:26759593661:ios:6ee7988e45bb98e92181d4',
    messagingSenderId: '26759593661',
    projectId: 'mi-vecino-seguro',
    storageBucket: 'mi-vecino-seguro.firebasestorage.app',
    iosBundleId: 'com.vecinoseguro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASB2BL-5BSpWCWwyWYSzsVr7P7GbiBOBM',
    appId: '1:26759593661:ios:177d5175afdb3ff52181d4',
    messagingSenderId: '26759593661',
    projectId: 'mi-vecino-seguro',
    storageBucket: 'mi-vecino-seguro.firebasestorage.app',
    iosBundleId: 'com.example.appVecinoSeguro',
  );
}
